#! /bin/bash

INTERFACE=$1
STATUS=$2

help() {
  echo "Usage: enable_network_interface <interface> <up|down>"
  echo "e.g. ./enable_network_interface enp0s8 up"
}

if [ $# -lt 2 ]; then
  help
  exit 1
elif [ `whoami` != "root" ]; then
  echo "Please re-run as root"
  exit 1
fi

ip link set $INTERFACE $STATUS
